name:                simulator

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Werror
  dependencies:
    - extra
    - containers

executables:
  simulator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wunused-imports
    - -Werror
    - -O2
    # - -funbox-strict-fields
    dependencies:
    - simulator
    - optparse-generic

tests:
  simulator-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O0
    dependencies:
    - simulator
    - tasty
    - tasty-hunit
    - extra
    - heap

benchmarks:
  simulator-benchmarks:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - simulator
    - criterion
