name:                simulator

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: lib
  ghc-options:
    - -Wall
    - -Werror
  dependencies:
    - extra
    - split

executables:
  simulator:
    main:                Main.hs
    source-dirs:         simulator
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wunused-imports
    - -Werror
    - -O2
    dependencies:
    - simulator
    - optparse-generic

  instance-generator:
    main:                Main.hs
    source-dirs:         instance-generator
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wunused-imports
    - -Werror
    - -O2
    dependencies:
    - optparse-generic
    - random

tests:
  simulator-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O0
    dependencies:
    - simulator
    - tasty
    - tasty-hunit
    - extra
    - heap

benchmarks:
  simulator-benchmarks:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - simulator
    - criterion
